package co.mgentertainment.common.syslog.dal.po;

import java.util.Date;

public class SysLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.title
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.service_id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remote_addr
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String remoteAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_agent
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_uri
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String requestUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.method
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.del_flag
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.update_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.update_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.opration_module
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String oprationModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.opration_text
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String oprationText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.opration_type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String oprationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.params
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.exception
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    private String exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.type
     *
     * @return the value of sys_log.type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.type
     *
     * @param type the value for sys_log.type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.title
     *
     * @return the value of sys_log.title
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.title
     *
     * @param title the value for sys_log.title
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.service_id
     *
     * @return the value of sys_log.service_id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.service_id
     *
     * @param serviceId the value for sys_log.service_id
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remote_addr
     *
     * @return the value of sys_log.remote_addr
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remote_addr
     *
     * @param remoteAddr the value for sys_log.remote_addr
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr == null ? null : remoteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_agent
     *
     * @return the value of sys_log.user_agent
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_agent
     *
     * @param userAgent the value for sys_log.user_agent
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_uri
     *
     * @return the value of sys_log.request_uri
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_uri
     *
     * @param requestUri the value for sys_log.request_uri
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri == null ? null : requestUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.method
     *
     * @return the value of sys_log.method
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.method
     *
     * @param method the value for sys_log.method
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.time
     *
     * @return the value of sys_log.time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.time
     *
     * @param time the value for sys_log.time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.del_flag
     *
     * @return the value of sys_log.del_flag
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.del_flag
     *
     * @param delFlag the value for sys_log.del_flag
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.update_time
     *
     * @return the value of sys_log.update_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.update_time
     *
     * @param updateTime the value for sys_log.update_time
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_by
     *
     * @return the value of sys_log.create_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_by
     *
     * @param createBy the value for sys_log.create_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.update_by
     *
     * @return the value of sys_log.update_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.update_by
     *
     * @param updateBy the value for sys_log.update_by
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.opration_module
     *
     * @return the value of sys_log.opration_module
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getOprationModule() {
        return oprationModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.opration_module
     *
     * @param oprationModule the value for sys_log.opration_module
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setOprationModule(String oprationModule) {
        this.oprationModule = oprationModule == null ? null : oprationModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.opration_text
     *
     * @return the value of sys_log.opration_text
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getOprationText() {
        return oprationText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.opration_text
     *
     * @param oprationText the value for sys_log.opration_text
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setOprationText(String oprationText) {
        this.oprationText = oprationText == null ? null : oprationText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.opration_type
     *
     * @return the value of sys_log.opration_type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getOprationType() {
        return oprationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.opration_type
     *
     * @param oprationType the value for sys_log.opration_type
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setOprationType(String oprationType) {
        this.oprationType = oprationType == null ? null : oprationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.params
     *
     * @return the value of sys_log.params
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.params
     *
     * @param params the value for sys_log.params
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.exception
     *
     * @return the value of sys_log.exception
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.exception
     *
     * @param exception the value for sys_log.exception
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Aug 21 11:10:18 GST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", remoteAddr=").append(remoteAddr);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", requestUri=").append(requestUri);
        sb.append(", method=").append(method);
        sb.append(", time=").append(time);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", oprationModule=").append(oprationModule);
        sb.append(", oprationText=").append(oprationText);
        sb.append(", oprationType=").append(oprationType);
        sb.append(", params=").append(params);
        sb.append(", exception=").append(exception);
        sb.append("]");
        return sb.toString();
    }
}